name: Setup Runner
description: Setup Node, Authenticate and install packages

# Adapted from https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

runs:
  using: composite
  steps:
    # Set up Node
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    # clean-install all npm packages
    - name: Install
      shell: bash -leo pipefail {0}
      run: npm ci
