name: 'PR Checker'

# **What it does**: Runs unit tests before allowing PRs to merge.
# **Why we have it**: To make sure all unit tests pass
# **Who does it impact**: Devs who want to merge PRs

# Adapted from https://docs.github.com/en/actions/examples/using-scripts-to-test-your-code-on-a-runner

on:
  workflow_dispatch:
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: 'ubuntu-latest'
    steps:
      - name: Add /usr/local/bin to PATH
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup, Authenticate, and Install
        uses: ./.github/actions/setup-runner

      - name: Run Unit tests
        run: npm run test

  check-formatting:
    name: Check Formatting
    runs-on: 'ubuntu-latest'
    steps:
      - name: Add /usr/local/bin to PATH
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup, Authenticate, and Install
        uses: ./.github/actions/setup-runner

      - name: Check Formatting
        run: npm run check:format

  linting:
    name: Linting
    runs-on: 'ubuntu-latest'
    steps:
      - name: Add /usr/local/bin to PATH
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup, Authenticate, and Install
        uses: ./.github/actions/setup-runner

      - name: Linting
        run: npm run check:lint
